06_Django/django13/수업/articles/urls.py
# URL설정을 app 단위로!
from django.urls import path
from . import views


app_name = "articles"

urlpatterns = [
    # http://127.0.0.1:8000/articles/
    path("", views.index, name="index"),
    # http://127.0.0.1:8000/articles/new/
    # path('new/', views.new, name='new'),
    # http://127.0.0.1:8000/articles/create/
    path("create/", views.create, name="create"),
    # http://127.0.0.1:8000/articles/1/ : 1번글
    # http://127.0.0.1:8000/articles/3/ : 3번글
    path("<int:pk>/", views.detail, name="detail"),
    # http://127.0.0.1:8000/articles/1/update/ : 1번글 수정
    # http://127.0.0.1:8000/articles/3/update/ : 3번글 수정
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

06_Django/django13/수업/articles/models.py
# imagekit 설정
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.
# 1. 모델 설계 (DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )

    # 어디에 이미지 업로드 할지 이미지는 항상 업로드하는게 아니기 때문에

06_Django/django13/수업/articles/forms.py
from email.mime import image
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image"]

06_Django/django13/수업/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleForm
from django.contrib import messages

# Create your views here.

# 요청 정보를 받아서..
def index(request):
    # 게시글을 가져와서..
    articles = Article.objects.order_by("-pk")
    # Template에 전달한다.
    context = {"articles": articles}
    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            article_form = ArticleForm(request.POST, request.FILES)
            if article_form.is_valid():
                article_form.save()
                messages.success(request, "글 작성이 완료되었습니다.")
                return redirect("articles:index")
        else:
            article_form = ArticleForm()
        context = {"article_form": article_form}
        return render(request, "articles/form.html", context=context)
    else:
        # 다양한 해결책 존재
        # 로그인창으로 보내기
        return redirect("accounts:login")


def detail(request, pk):
    # 특정 글을 가져온다.
    article = Article.objects.get(pk=pk)
    # template에 객체 전달
    context = {"article": article}
    return render(request, "articles/detail.html", context)


from django.contrib.auth.decorators import login_required


@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 값 가져와서, 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, request.FILES, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 저장하고, 상세보기 페이지로
            article_form.save()
            messages.success(request, "글이 수정되었습니다.")
            return redirect("articles:detail", article.pk)
        # 유효성 검사 통과하지 않으면 => context 부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)
    context = {"article_form": article_form}
    return render(request, "articles/form.html", context)


@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect("articles:index")

06_Django/django13/수업/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %} 
<h1>{{ article.pk }}번 게시글</h1>
<p>{{ article.created_at|date:"y-m-d D" }} | {{ article.updated_at|date:"y-m-d D" }}</p>
<h2>{{ article.content }} </h2>
{% comment %} {%if requset.user == article.user %} 다음주 수업 {% endcomment %} 
{% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image }}" width="400" height="300">
{% endif %}
<div>
  <a href="{% url 'articles:update' article.pk %}"class="btn btn-outline-dark my-3">수정하기</a>
  <a href="{% url 'articles:delete' article.pk %}"class="btn btn-outline-dark my-3">삭제하기</a>
</div>
{% endblock %}

06_Django/django13/수업/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}

{% endblock %}

{% block body %} 
<h1>게시글</h1>
<div class = 'row'>
  {% for article in articles %}
  <div class ='col-4'>
    <div class="card h-100">
      <img src="{{article.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <div class='d-flex justify-content-between'>
          <h4 class="card-title align-self-center">{{ article.title }}</h4>
          <a href="{% url 'articles:detail' article.pk %}" class="btn btn-outline-dark my-3">상세보기</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}