06_Django/django09/실습/movies/urls.py
from django.urls import path 
from . import views

app_name = 'movies'
urlpatterns =[
    path('', views.index, name='index'),
    path('create/',views.create, name='create'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name="update"),
    path('<int:pk>/delete/',views.delete, name='delete'),

]

06_Django/django09/실습/project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
]

06_Django/django09/실습/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=80)
    summary = models.TextField() 
    running_time = models.IntegerField()

06_Django/django09/실습/movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        # editable field만 가능.
        fields = ['title', 'summary','running_time']

06_Django/django09/실습/movies/views.py
import imp
from django.shortcuts import redirect, render
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }   
    return render (request, 'movies/index.html',context)

def create(request):
    if request.method == 'POST':
        movie_form = MovieForm(request.POST)
        if movie_form.is_valid():
            movie_form.save()
            return redirect('movies:index')
    else:
        movie_form = MovieForm()
    context = {
        'movie_form' : movie_form,
    }
    return render(request, 'movies/new.html',context)

def detail(request,pk):
    movie = Movie.objects.get(pk=pk)
    context ={
    'movie' : movie,
    }
    return render(request,'movies/detail.html',context)

def update(request,pk ):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        movie_form = MovieForm(request.POST , instance=movie)
        if movie_form.is_valid():
            movie_form.save()
            return redirect('movies:detail', movie.pk)
    else:
        movie_form = MovieForm(instance=movie)
    context = {
        'movie_form' : movie_form,
    }
    return render(request, 'movies/update.html',context)        

def delete(request,pk):
    movie=Movie.objects.get(pk=pk)
    movie.delete()
    return redirect("movies:index")
    

06_Django/django09/실습/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <form action="" method='post'>
    {% csrf_token %}
    <div class='mx-5 px-5'>
      <div class='d-flex flex-row justify-content-between'>
        <h3>{{movie.title}}</h3>
        <p>{{movie.running_time}}
          분</p>
      </div>
      <hr>
      <p>{{movie.summary}}</p>

      <a class="btn btn-primary  btn-sm" href="{%url 'movies:update' movie.pk%}">수정</a>
      <a class="btn btn-primary  btn-sm" href="{%url 'movies:delete' movie.pk%}">삭제</a>

    </div>
  </form>
{% endblock %}

06_Django/django09/실습/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <table class="table">
    <thead>
      <tr>
        <th class="col-2">pk</th>
        <th class="col">영화제목</th>
      </tr>
    </thead>
    {% for movie in  movies%}
      <tbody>
        <tr>
          <th scope="row">
            {{movie.pk}}
          </th>
          <td>
            <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
          </td>
        </tr>
      </tbody>
    {% endfor %}
  </table>
{% endblock %}

06_Django/django09/실습/movies/templates/movies/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form movie_form %}
    <input type="submit" href='' value='추가' class='btn btn-primary'>

  </form>
{% endblock %}

06_Django/django09/실습/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form movie_form %}

    <input type="submit" href='' value='수정' class='btn btn-primary'>

  </form>

{% endblock %}

06_Django/django09/실습/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class=" container-fluid">
        {% comment %} {%load static%}
        <img src="{% static 'movie.jpeg'%}" alt=""> {% endcomment %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:index'%}">목록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:create'%}">추가</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">

      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>